name: Publish to PyPI

on:
  push:
    tags:
      - '*'


jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        poetry-version: [ "1.7.1" ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
        poetry-plugins: "poetry-dynamic-versioning[plugin]"
    - name: build sdist
      run: poetry build

    - name: Save sdist
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz

    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1